### ISSUE TITLE
Duplicate columns created for foreign key columns

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#12]
The foreign key columns are created but they are created with duplicate columns:
- one with no relation and having the correct name
- the other one with a wrong name (using the parent as name) but having a correct relation

See the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/17274117/943febdc-56d9-11e6-8f7b-2fb1055641c9.png)

From the image, parcel_id, person_id, and institution_id has the correct name but with no relation and the next three columns parcel, person and institution has relation but not the correct name.

**Comment by geonomad-consulting** [comment]
I think this [commit](https://github.com/geonomad-consulting/stdm/commit/dd18ddf954d5b18f8e98cb5c1ec66571c58eb224) has fixed the issue

**Comment by wondie** [comment]
I have tested it. The columns with a wrong name are removed but the foreign key relation is not integrated to the columns with the correct name.

**Comment by geonomad-consulting** [comment]
What should be the correct format for the foreign key?

**Comment by wondie** [comment]
You have already done it on the columns that you have removed. Their foreign key constraint was specified properly but the column name was not correct. For instance, when it was supposed to be parcel_id, its name was parcel, which I think came from foreign key parent name. So you just need to change that part and remove the creation of the second column which doesn't have foreign key. I hope I am clear, if not, I can explain by phone.

**Comment by wondie** [comment]
This issue is now fixed!
