### ISSUE TITLE
Foriegn Key and Lookup columns do not use display columns

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#13]
In the new configuration, there is displayColumns that is used to avoid showing users id of foreign keys. In entity browser. This displayColumns is not added at all in the upgraded configuration.stc

Taken from configuration.stc
For lookups and foreign keys

```
<EntityRelation displayColumns="name,code" child="Person" parent="check_gender" name="fk_in_check_gender_id_in_person_gender" parentColumn="id" childColumn="gender"/>
<EntityRelation displayColumns="code" child="Survey" parent="Parcel" name="fk_lo_parcel_id_lo_survey_parcel" parentColumn="id" childColumn="parcel"/>
```

**Comment by geonomad-consulting** [comment]
This issue has been fixed with this [commit](https://github.com/geonomad-consulting/stdm/commit/f1123b21ce027cd436b923416bd29ada38514e5a)

**Comment by wondie** [comment]
I have confirmed that it is fixed.
