### ISSUE TITLE
QGIS hangs when re-upgrading while the new config tables exists

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#14]
I first run the updater and it worked with no crash on an old database with data. 
Then I upgraded again without removing the database. Then QGIS hangs. 

This might be due to the absence of check if pg_table_exists() ba_party and inability to check if a profile with a prefix exists in the database. 

Edit: This issue is also related to issue #11 so if you know if a duplicate profile exists, update it than trying to create it from scratch. The Configuration Wizard does something like that so there is a support for this behavior in the new configuration.

**Comment by geonomad-consulting** [comment]
This issue can't be reproduced on my system. If it appears again report, otherwise close the issue

**Comment by wondie** [comment]
The issue is now fixed.
