### ISSUE TITLE
Typo fix displayColumn to displayColumns for non str relations

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#16]
The displayColumns is wrongly typed as displayColumn in all relations other than STR.

**Comment by geonomad-consulting** [comment]
This issue is now fixed with this [commit](https://github.com/geonomad-consulting/stdm/commit/1e8b7f7438949e5bd94fdd81a1af845266774c2c)

**Comment by wondie** [comment]
Yes it is fixed now.
