### ISSUE TITLE
The profile name case has changed in the generated configuration.stc 

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#2]
Even though the case of the profile name was title case, in the generated configuration.stc, it became lower case. It would be good to maintain the case. Most importantly, I have learned from Paul that the new configuration's profile names should NOT have a space. Spaces need to be replaced by underscore.

**Comment by geonomad-consulting** [comment]
This has been fixed via [commit](https://github.com/geonomad-consulting/stdm/commit/88a3db83fe68d75823e4a5293bd063ff49c2460d)

**Comment by wondie** [comment]
I have also confirmed that it is working.
