### ISSUE TITLE
Typo and inconsitency in party and spatial_unit supporting document relation

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#32]
There is a typo in spatial_unit supporting document relation. 
The relation name looks like this. 
fk_baparty_id_ba_party_supporting_document_party_id
fk_baspatial_unit_id_ba_spatial_unit_supporting_document_spatial_unit_id

But it should be 
fk_ba_party_id_ba_party_supporting_document_party_id
fk_ba_spatial_unit_id_ba_spatial_unit_supporting_document_spatial_unit_id

It is correctly written in the database. 
![image](https://cloud.githubusercontent.com/assets/9709624/17768167/86231fea-653b-11e6-85ac-2b2819ccda37.png)

**Comment by geonomad-consulting** [comment]
@wondie I think this is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/66d6564109aecfc3c7edec4403f6fdb02ba6106c) please test and revert

**Comment by wondie** [comment]
This is fixed!
