### ISSUE TITLE
ConfigUpdated registry key error

### ISSUE THREAD

**Issue by geonomad-consulting** [geonomad-consulting/stdm#35]
@wondie I get the [error](https://gist.github.com/geonomad-consulting/017fded64b3c645a59ee2beb83a96945) below when adding registry key what could be the issue?

![image](https://cloud.githubusercontent.com/assets/17067856/17799030/c9069590-65df-11e6-9e14-d4e791752d48.png)

**Comment by wondie** [comment]
Could you push the changes so that I can see the whole code.

**Comment by geonomad-consulting** [comment]
Okay. This only poped up the first time so I moved the call statement that looks at the dictionary after writing the value and not before, if it done before it throws the keyerror, that's when it worked as below.

`
                # if config file exists, check if registry key exists
                if len(config_updated_dic) < 1:
                    # if it doesn't exist, create it with a value of False (
                    # '0')
                    self.reg_config.write({'ConfigUpdated': '0'})

```
            config_updated_val = config_updated_dic[CONFIG_UPDATED]
```

`

**Comment by wondie** [comment]
So is it solved now?

**Comment by geonomad-consulting** [comment]
This issue is fixed.
