### ISSUE TITLE
Configuration file cannot be loaded error

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#36]
I couldn't run the upgrade process and start stdm because of the following error. 
It shows, neither the configuration.stc file is copied nor the upgrade of stdmConfig.xml happens. 
![image](https://cloud.githubusercontent.com/assets/9709624/17800734/56417cf0-65ee-11e6-9646-6c00c19ba723.png)
Edit: The registry key ConfigUpdated is added in the stdm registry key with a value of -1

**Comment by geonomad-consulting** [comment]
Is this still an issue?

**Comment by wondie** [comment]
It is no longer there.
