### ISSUE TITLE
If stdmConfig.xml exists, the popup to backup database appears even if configuration.stc exists

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#4]
If stdmConfig.xml exists, the popup to backup database appears even if configuration.stc exists. I guess this is for testing. Because, if a user already has configuration.stc even if there is stdmConfig.xml, the upgrade shouldn't run. Because, a user might accidentally keep a stdmConfig.xml and when stdm starts, it could overwrite the existing configuration.stc. [ This post ](https://github.com/gltn/stdm/issues/120#issuecomment-232562656) of John explains it the behavior.

**Comment by geonomad-consulting** [comment]
I think this issue has already been fixed by having stdmConfig.xml renamed. The behavior now ill be that if configuration.stc exists, then no upgrade pop up will show.

**Comment by wondie** [comment]
You mean if no stdmConfig.xml?
