### ISSUE TITLE
A full profile dictionary returned from the config_updater than a tuple of profile prefix and old entity names

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#40]
A full profile dictionary returned from the config_updater at line 583-584 in the plugin.py (see the code block at the bottom).
 Line 583-584,  plugin.py

```
   profile_entity_lookup_rltns = \
                    self.configuration_file_updater.backup_data()
```

`
OrderedDict([(u'Basic', OrderedDict([(u'Basic_table', OrderedDict([(u'party', [u'Party can be a person household or group', u'Party can be a person household or group', OrderedDict([('col_name', u'id'), ('col_search', u''), ('col_descrpt', u'Primary Key'), ('parent', None), ('col_type', 'SERIAL'), ('lookup', None)]), OrderedDict([('col_name', u'family_name'), ('col_search', u'yes'), ('col_descrpt', u'Surname'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'other_names'), ('col_search', u'yes'), ('col_descrpt', u'other given names'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'address'), ('col_search', u''), ('col_descrpt', u'address id'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'identification'), ('col_search', u'yes'), ('col_descrpt', u'Identification'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'contact_telephone'), ('col_search', u''), ('col_descrpt', u'mobile'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'date_of_birth'), ('col_search', u'no'), ('col_descrpt', u'date of birth'), ('parent', None), ('col_type', 'DATE'), ('lookup', None)]), OrderedDict([('col_name', u'gender'), ('col_search', u'no'), ('col_descrpt', u'sex'), ('parent', None), ('col_type', 'LOOKUP'), ('lookup', u'check_gender')]), OrderedDict([('col_name', u'household_relation'), ('col_search', u'yes'), ('col_descrpt', u''), ('parent', None), ('col_type', 'LOOKUP'), ('lookup', u'check_household_relation')]), OrderedDict([('col_name', u'signature'), ('col_search', u''), ('col_descrpt', u'signature'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)])]), (u'spatial_unit', [u'spatial unit or a group of spatial unit', u'spatial unit or a group of spatial unit', OrderedDict([('col_name', u'id'), ('col_search', u''), ('col_descrpt', u'Primary Key'), ('parent', None), ('col_type', 'SERIAL'), ('lookup', None)]), OrderedDict([('col_name', u'code'), ('col_search', u'yes'), ('col_descrpt', u'unique identifier'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'name'), ('col_search', u'yes'), ('col_descrpt', u'Friendly name of the unit'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'type'), ('col_search', u'yes'), ('col_descrpt', u'type of the unit'), ('parent', None), ('col_type', 'LOOKUP'), ('lookup', u'check_type')]), OrderedDict([('col_name', u'sp_unit_use'), ('col_search', u'yes'), ('col_descrpt', u'Use'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'geom_polygon'), ('col_search', 'no'), ('col_descrpt', ''), ('lookup', None), ('col_type', OrderedDict([('srid', u'4326'), ('type', '2')]))])]), (u'supporting_document', [u'Prove of evidence to the defined tenure', u'Prove of evidence to the defined tenure', OrderedDict([('col_name', u'id'), ('col_search', u''), ('col_descrpt', u'Primary Key'), ('parent', None), ('col_type', 'SERIAL'), ('lookup', None)]), OrderedDict([('col_name', u'document_type'), ('col_search', u''), ('col_descrpt', u''), ('parent', None), ('col_type', 'LOOKUP'), ('lookup', u'check_document_type')]), OrderedDict([('col_name', u'date_of_recording'), ('col_search', u''), ('col_descrpt', u'when it was obtained'), ('parent', None), ('col_type', 'DATE'), ('lookup', None)]), OrderedDict([('col_name', u'validity'), ('col_search', u''), ('col_descrpt', u'Validity period'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'source'), ('col_search', u''), ('col_descrpt', u'From whom/ where'), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'document_id'), ('col_search', u''), ('col_descrpt', u''), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'filename'), ('col_search', u''), ('col_descrpt', u''), ('parent', None), ('col_type', 'VARCHAR'), ('lookup', None)]), OrderedDict([('col_name', u'doc_size'), ('col_search', u''), ('col_descrpt', u'Document Size'), ('parent', None), ('col_type', 'INT'), ('lookup', None)])]), (u'social_tenure_relationship', [u'Relation of the person to spatial unit as supported by supporting documents', u'Relation of the person to spatial unit as supported by supporting documents', OrderedDict([('col_name', u'id'), ('col_search', u''), ('col_descrpt', u'Primary Key'), ('parent', None), ('col_type', 'SERIAL'), ('lookup', None)]), OrderedDict([('col_name', u'social_tenure_type'), ('col_search', u'yes'), ('col_descrpt', u'type of social tenure'), ('parent', None), ('col_type', 'LOOKUP'), ('lookup', u'check_social_tenure_type')]), OrderedDict([('col_name', u'share'), ('col_search', u''), ('col_descrpt', u'share unit '), ('parent', None), ('col_type', 'DOUBLE'), ('lookup', None)]), OrderedDict([('col_name', u'party'), ('col_search', u''), ('col_descrpt', u'party id'), ('parent', None), ('col_type', 'INT'), ('lookup', None)]), OrderedDict([('col_name', u'spatial_unit'), ('col_search', u''), ('col_descrpt', u'spatial unit id'), ('parent', None), ('col_type', 'INT'), ('lookup', None)])]), (u'str_relations', [u'table for store str id and supporting documents', u'table for store str id and supporting documents', OrderedDict([('col_name', u'id'), ('col_search', u''), ('col_descrpt', u'Primary Key'), ('parent', None), ('col_type', 'SERIAL'), ('lookup', None)]), OrderedDict([('col_name', u'social_tenure_id'), ('col_search', u'no'), ('col_descrpt', u'Social tenure relation primary key'), ('parent', None), ('col_type', 'INT'), ('lookup', None)]), OrderedDict([('col_name', u'source_doc_id'), ('col_search', u'no'), ('col_descrpt', u'Primary key of the supporting document'), ('parent', None), ('col_type', 'INT'), ('lookup', None)])])])), (u'Basic_lookup', OrderedDict([(u'check_document_type', OrderedDict([(u'AU', u'Audio Files'), (u'VI', u'Video Files'), (u'RE', u'Rent certificate'), (u'LE', u'Lease agreement'), (u'TI', u'Title')])), (u'check_social_tenure_type', OrderedDict([(u'IN', u'Individual owner'), (u'JO', u'Joint ownership with spouse'), (u'CH', u'Child of owner'), (u'WI', u'Wife of owner'), (u'RE', u'Relative'), (u'HU', u'Husband of owner')])), (u'check_gender', OrderedDict([(u'MA', u'Male'), (u'FE', u'Female')])), (u'check_marital_status', OrderedDict([(u'MA', u'married'), (u'SI', u'Single'), (u'DI', u'Divorced'), (u'WI', u'widow')])), (u'check_household_relation', OrderedDict([(u'HU', u'Husband'), (u'WI', u'Wife'), (u'DA', u'Daughter'), (u'SO', u'Son'), (u'IN', u'In-law'), (u'GR', u'Grand child'), (u'MO', u'Mother'), (u'CO', u'Cousin'), (u'SI', u'Sister'), (u'BR', u'Brother'), (u'NI', u'Niece'), (u'NE', u'Nephew')])), (u'check_type', {'G': 'General'}), ('check_spatial_unit_document_type', {'G': 'General'}), ('check_party_document_type', {'G': 'General'})])), (u'Basic_relations', {u'social_tenure_relationship': [[u'spatial_unit', u'id', u'spatial_unit', u''], [u'party', u'id', u'party', u'']], u'str_relations': [[u'social_tenure_relationship', u'id', u'social_tenure_id', u'id'], [u'supporting_document', u'id', u'source_doc_id', u'id']]})])), (u'urban', OrderedDict([(u'urban_table', OrderedDict()), (u'urban_lookup', OrderedDict()), (u'urban_relations', {})]))])`

 Instead, what I need to the template updater is the following. 
profile prefix, [party, spatial_unit, social_tenure_relationship, etc]

**Comment by eomwandho** [comment]
Hi Wondie what do you want returned from the module? Old entities names or
new entities names?

The current dictionary contains a dictionary as the outer key being the
profile name from where you can extract the prefix, the names of the old
table are included in an inner dictionary key called {profile name}_table,
lookups using key {profile name}_lookup, and relations where you can get
from {profile name}_relations.

**Comment by wondie** [comment]
Hi Erick, the whole old configuration dictionary is not what I want. Having that means, I have to do a filtering of table names, exclusions, etc which is really a duplicate work on my side. As you have already done that, it will mean **we will repeat ourselves** again.

Also, I don't want to get the profile prefix from the profile name as you have already done the same thing. 

Thus, what I suggest is, just to have the profile name, prefix, and list of all old tables (including lookups) only. To do this, I am sure you might already have a variable called  self.table_dict, self.table_list, etc. If they are for the old tables, that is what I want.

**Comment by wondie** [comment]
There is one change. Exclude profile prefix from the return.

**Comment by wondie** [comment]
I think this is simple. So we can do it when we meet tomorrow but if you have time, you can populate a dictionary called profile detail. It will have a class variable `self.profiles_detail`. It is populated in 
`self._create_entity_valuelist_relation_nodes()`

Here the dictionary will look like the following. 

```
self.profiles_detail = {}
self.profiles_detail['profile_1'] = {'old_table':'new_table'}
```

result `self.profiles_detail = {'prof': {'old_table': 'new_table'}}`
When adding a other tables in the same profile
self.profiles_detail['profile_1'].update({'old_table_2': 'new_table_2'})
result `self.profiles_detail = {'profile_1': {'old_table_2': 'new_table_2', 'old_table': 'new_table'}}`

If you are adding new profile the self.profiles_detail will look like the following. 
`self.profiles_detail = {'profile_1': {'old_table_2': 'new_table_2', 'old_table': 'new_table'}, 'profile_2': {'old_table_2': 'new_table_2', 'old_table': 'new_table'}}`

**Comment by geonomad-consulting** [comment]
This is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/07b087d2433557bcf00eca6c93893170f8d9b7b1)

**Comment by wondie** [comment]
I have confirmed the issue is fixed.
