### ISSUE TITLE
Some columns are empty in the new supporting document table

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#41]
There are empty columns in the supporting document table even though they have data in the old table and some of the values are known as it is default. 

The document size already exists in the old table but not imported.
source_entity is the social tenure relationship entity name. 
Creation date also exists in both tables. 

Old table
![image](https://cloud.githubusercontent.com/assets/9709624/17812994/22886c4a-6632-11e6-8c51-18c86c1f5a66.png)

New table
![image](https://cloud.githubusercontent.com/assets/9709624/17812969/0d5d8378-6632-11e6-8d27-55c541978bcb.png)

**Comment by geonomad-consulting** [comment]
In my database is empty, though I can still get and add it. What is the file format size byte, kilobyte?

**Comment by geonomad-consulting** [comment]
The size column in my database of the supporting_document is empty as shown below

![image](https://cloud.githubusercontent.com/assets/17067856/17848625/24719324-685d-11e6-8f0a-8a5e4ceb6dee.png)

**Comment by wondie** [comment]
Yea, that is the outdated Zambian data but there is still a column called document_size which is the same as doc_size.

**Comment by geonomad-consulting** [comment]
I think this has been fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/2507d75fa79eddd6ca35dfe80947b6a81a6bb3d8)

**Comment by geonomad-consulting** [comment]
Disregard the above [commit](https://github.com/geonomad-consulting/stdm/commit/2507d75fa79eddd6ca35dfe80947b6a81a6bb3d8) instead using this [one](https://github.com/geonomad-consulting/stdm/commit/74725bb100ec9fa682f52908b2ed98fe52c0b08f)

**Comment by wondie** [comment]
I will check and report later.

**Comment by geonomad-consulting** [comment]
I think this issue is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/73b97d1344adbc763c0bb9c0e0c2c6a178bf983e)

**Comment by wondie** [comment]
This issue is now fixed.
