### ISSUE TITLE
Improving the behavior of the upgrade  and the popup message

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#6]
Edited:
1. I feel it is important to keep the old configuration. This is because, upgrade process might fail and users will be unable to do the same process again. 
1. We can confidently assume users will always want to move their data that they are currently using in the new version. So we don't need to ask users the question of copying or not. 
2. In stead, the popup should ask users to upgrade the configuration than just backing up data. Thus, unless the user agree the creation of the configuration.stc shouldn't happen. Meaning, the upgrade shouldn't happen until the user agree to upgrade. 
3. If there was a failed upgrade, the upgrade popup should appear. 
4. The upgrade process shouldn't overwrite existing configuration.stc. Insead, it should append the profile. Because, users might modify their configuration.stc. 
5. I suggest an Upgrade button to be included in Options Module so that users can then choose to upgrade manually. 

Once issue #4  is fixed, I suggest you to add a registry key, UpgradedConfig with values 
True, False and None. 
**True** - if the user has successfully upgraded the data
**False** - if the the upgrade process failed. The user will continue to see the popup on every restart until a successful upgrade or the user hides the popup by clicking the checkbox explained below.
**None** - if the user never want to see the popup again or if the user have installed STDM for the first time or doesn't have stdmConfig.xml in .stdm directory. 
 If the user select the checkbox, _"I don't want upgrade my old configuration and copy my data. Don't show me this message again"_. This will result in the registry value to change from False to None.  And the default configuration.stc to load. But still the old stdmConfig.xml will not be deleted. 

Manual Upgrade - the user can still run the upgrade using the STDM Options. 

Thus, to comply with the above behavior the popup message to should look something like this. 

```
Do you want to upgrade your configuration to the new version? 

If you click No, your configuration and data will no longer be accessible to STDM.

Checkbox - I don't want upgrade my old configuration and copy my data. Don't show me this message again.

                                                Yes            No
```

On successful upgrade, a popup should show:
`
Your configuration is successfully upgraded!
`
On failed upgrade, a popup should show;

```
Sorry, the upgrade process failed. 
We couldn't upgrade the configuration
```

or 

```
We couldn't copy the data to STDM 1.2.
With the escaped python error message. 

```

**Comment by geonomad-consulting** [comment]
This issue has being agreed to be moved to another release.

**Comment by wondie** [comment]
No matter what, it is not solved yet, so it should be left open so that we don't forget it.
