### ISSUE TITLE
The SRID set in stdmConfig.xml is note picked instead 4326 is used

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#7]
The SRID set in stdmConfig.xml is note used when copying the database instead 4326 is used. The stdmConfig and the table used SRID - 21096 but the table created by the upgrade tool uses SRID 4326.

**Comment by geonomad-consulting** [comment]
This issue is fixed via [commit](https://github.com/geonomad-consulting/stdm/commit/70c35376b4a793d723b0f565d7a3b30093a44be9)
